name: PackSquash On Tag
on:
  push:
    tags:
      - '**'

jobs:
  packsquash:
    strategy:
      matrix:
        pack: [vanilla, cartoon, chinese-mythology, city, fallout, fantasy, festive, greek-mythology, halloween, natural, plastic, steampunk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1.10
        with:
          repository: 'ComunidadAylas/PackSquash'
          latest: true
          fileName: 'PackSquash.CLI.executable.x86_64-unknown-linux-musl.zip'
          out-file-path: 'Packs'

      - name: Extract
        working-directory: ./Packs
        run: 7z x 'PackSquash CLI executable (x86_64-unknown-linux-musl).zip'

      - name: CHMOD
        working-directory: ./Packs
        run: chmod +x packsquash

      - name: Squash All Packs
        working-directory: ./Packs
        run: |
          chmod +x packsquash
          mkdir out
          printf "allow_mods = ['OptiFine']\nzip_spec_conformance_level = 'disregard'\nnever_store_squash_times = true\npack_directory = \"%s\"\noutput_file_path = \"out/%s.zip\"" "${{ matrix.pack }}" "${{ matrix.pack }}"> packsquash-options.toml
          ./packsquash packsquash-options.toml

      - name: Release Packs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Packs/out/${{ matrix.pack }}.zip"
          allowUpdates: true